services:
  - type: web
    name: bia601-ga-app # Your service name on Render (you can change it)
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn bia601_project.wsgi:application"
    
    plan: free 
    
    envVars:
      - key: SECRET_KEY
        generateValue: true
      
      - key: DATABASE_URL
        fromDatabase:
          name: bia601-project-db # Render DB name (ensure you create a Postgres instance first)
          property: connectionString
      - key: DEBUG
        value: False